export const List = [
  {
    name: "Open Source Contribution Program",
    logo: "opensource-logo.png",
    date: "21 Jan - 15 Apr",
    type: "Open Source",
    stipend: "No",
    duration: "3M",
    location: ["Remote", "San Francisco", "Bangalore"],
    education: [
      { "high school": "Yes" },
      { undergrad: "Any" },
      { stream: "Any" },
    ],
    gender: "Any",
  },
  {
    name: "Summer Internship 2024",
    logo: "internship-logo.png",
    date: "1 Jun - 31 Aug",
    type: "Internship",
    stipend: "1k-4k",
    duration: "3M",
    location: ["New York", "London", "Remote"],
    education: [{ undergrad: "1st & 2nd" }, { stream: "Any" }],
    gender: "Any",
  },
  {
    name: "CodeFest 2024",
    logo: "codefest-logo.png",
    date: "10 Mar - 12 Mar",
    type: "Hackathon",
    stipend: "No",
    duration: "3D",
    location: ["Mumbai", "Berlin"],
    education: [
      { "high school": "Yes" },
      { undergrad: "Any" },
      { stream: "Any" },
    ],
    gender: "Any",
  },
  {
    name: "AI Developer Position",
    logo: "ai-logo.png",
    date: "15 Feb - 15 Jul",
    type: "Job",
    stipend: "100-5k",
    duration: "5M",
    location: ["San Francisco", "Bangalore", "Remote"],
    education: [{ undergrad: "CSE only" }],
    gender: "Any",
  },
  {
    name: "Tech Innovators Fellowship",
    logo: "fellowship-logo.png",
    date: "1 Apr - 30 Sep",
    type: "Fellowship",
    stipend: "1k-4k",
    duration: "6M",
    location: ["Remote", "Tokyo"],
    education: [
      { postgrad: "Yes" },
      { phd: "Yes" },
      { working: "Yes" },
      { stream: "Any" },
    ],
    gender: "Any",
  },
  {
    name: "Cybersecurity Challenge 2024",
    logo: "cybersecurity-logo.png",
    date: "5 May - 25 May",
    type: "Competition",
    stipend: "No",
    duration: "3W",
    location: ["New York", "London", "Remote"],
    education: [{ undergrad: "1st & 2nd" }, { stream: "Any" }],
    gender: "Any",
  },
  {
    name: "Web Development Bootcamp",
    logo: "bootcamp-logo.png",
    date: "10 Jul - 30 Jul",
    type: "Training",
    stipend: "No",
    duration: "3W",
    location: ["Bangalore", "Berlin"],
    education: [{ school: "Yes" }, { undergrad: "Any" }, { stream: "Any" }],
    gender: "Any",
  },
  {
    name: "Digital Marketing Internship",
    logo: "marketing-logo.png",
    date: "15 Mar - 15 Aug",
    type: "Internship",
    stipend: "1k-4k",
    duration: "5M",
    location: ["San Francisco", "Mumbai", "Remote"],
    education: [{ undergrad: "Any" }, { stream: "Any" }],
    gender: "Any",
  },
  {
    name: "Blockchain Developer Challenge",
    logo: "blockchain-logo.png",
    date: "1 Sep - 30 Nov",
    type: "Competition",
    stipend: "No",
    duration: "3M",
    location: ["Tokyo", "New York"],
    education: [{ school: "Yes" }, { undergrad: "Any" }, { stream: "Any" }],
    gender: "Any",
  },
  {
    name: "Tech Entrepreneurship Workshop",
    logo: "entrepreneurship-logo.png",
    date: "5 Apr - 10 Apr",
    type: "Workshop",
    stipend: "No",
    duration: "1W",
    location: ["London", "Bangalore"],
    education: [
      { "high school": "Yes" },
      { undergrad: "Any" },
      { stream: "Any" },
    ],
    gender: "Any",
  },
];
